# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a7ac982a36746f8af533de42d3ecd23ab068896c1608b92c792ba3dddfba893349d342bc0697d7de5f8e0a6e1ee91335cc0f7efed630020e81e5812aabfbef0

test:
  secret_key_base: 233eaca6ae1b1bcc5dec4084fb5de6970096d30857809101f7765c63db19f54ba88a99e2bb412253ee17ce4f7ff8a91f294949e66e68c88dbeebace1e517a4b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
